/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.harper.testing.serde;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Base extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5676005631222858689L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Base\",\"namespace\":\"com.harper.testing.serde\",\"fields\":[{\"name\":\"f1\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"f2\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Base> ENCODER =
      new BinaryMessageEncoder<Base>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Base> DECODER =
      new BinaryMessageDecoder<Base>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Base> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Base> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Base>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Base to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Base from a ByteBuffer. */
  public static Base fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Integer f1;
  @Deprecated public java.lang.Long f2;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Base() {}

  /**
   * All-args constructor.
   * @param f1 The new value for f1
   * @param f2 The new value for f2
   */
  public Base(java.lang.Integer f1, java.lang.Long f2) {
    this.f1 = f1;
    this.f2 = f2;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return f1;
    case 1: return f2;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: f1 = (java.lang.Integer)value$; break;
    case 1: f2 = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'f1' field.
   * @return The value of the 'f1' field.
   */
  public java.lang.Integer getF1() {
    return f1;
  }

  /**
   * Sets the value of the 'f1' field.
   * @param value the value to set.
   */
  public void setF1(java.lang.Integer value) {
    this.f1 = value;
  }

  /**
   * Gets the value of the 'f2' field.
   * @return The value of the 'f2' field.
   */
  public java.lang.Long getF2() {
    return f2;
  }

  /**
   * Sets the value of the 'f2' field.
   * @param value the value to set.
   */
  public void setF2(java.lang.Long value) {
    this.f2 = value;
  }

  /**
   * Creates a new Base RecordBuilder.
   * @return A new Base RecordBuilder
   */
  public static com.harper.testing.serde.Base.Builder newBuilder() {
    return new com.harper.testing.serde.Base.Builder();
  }

  /**
   * Creates a new Base RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Base RecordBuilder
   */
  public static com.harper.testing.serde.Base.Builder newBuilder(com.harper.testing.serde.Base.Builder other) {
    return new com.harper.testing.serde.Base.Builder(other);
  }

  /**
   * Creates a new Base RecordBuilder by copying an existing Base instance.
   * @param other The existing instance to copy.
   * @return A new Base RecordBuilder
   */
  public static com.harper.testing.serde.Base.Builder newBuilder(com.harper.testing.serde.Base other) {
    return new com.harper.testing.serde.Base.Builder(other);
  }

  /**
   * RecordBuilder for Base instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Base>
    implements org.apache.avro.data.RecordBuilder<Base> {

    private java.lang.Integer f1;
    private java.lang.Long f2;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.harper.testing.serde.Base.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.f1)) {
        this.f1 = data().deepCopy(fields()[0].schema(), other.f1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.f2)) {
        this.f2 = data().deepCopy(fields()[1].schema(), other.f2);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Base instance
     * @param other The existing instance to copy.
     */
    private Builder(com.harper.testing.serde.Base other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.f1)) {
        this.f1 = data().deepCopy(fields()[0].schema(), other.f1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.f2)) {
        this.f2 = data().deepCopy(fields()[1].schema(), other.f2);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'f1' field.
      * @return The value.
      */
    public java.lang.Integer getF1() {
      return f1;
    }

    /**
      * Sets the value of the 'f1' field.
      * @param value The value of 'f1'.
      * @return This builder.
      */
    public com.harper.testing.serde.Base.Builder setF1(java.lang.Integer value) {
      validate(fields()[0], value);
      this.f1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'f1' field has been set.
      * @return True if the 'f1' field has been set, false otherwise.
      */
    public boolean hasF1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'f1' field.
      * @return This builder.
      */
    public com.harper.testing.serde.Base.Builder clearF1() {
      f1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'f2' field.
      * @return The value.
      */
    public java.lang.Long getF2() {
      return f2;
    }

    /**
      * Sets the value of the 'f2' field.
      * @param value The value of 'f2'.
      * @return This builder.
      */
    public com.harper.testing.serde.Base.Builder setF2(java.lang.Long value) {
      validate(fields()[1], value);
      this.f2 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'f2' field has been set.
      * @return True if the 'f2' field has been set, false otherwise.
      */
    public boolean hasF2() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'f2' field.
      * @return This builder.
      */
    public com.harper.testing.serde.Base.Builder clearF2() {
      f2 = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Base build() {
      try {
        Base record = new Base();
        record.f1 = fieldSetFlags()[0] ? this.f1 : (java.lang.Integer) defaultValue(fields()[0]);
        record.f2 = fieldSetFlags()[1] ? this.f2 : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Base>
    WRITER$ = (org.apache.avro.io.DatumWriter<Base>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Base>
    READER$ = (org.apache.avro.io.DatumReader<Base>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
